DROP TABLE IF EXISTS "DeliveryTask";
DROP TABLE IF EXISTS "ShiftSegment";
DROP TABLE IF EXISTS "Shift";
DROP TABLE IF EXISTS "User";
DROP TABLE IF EXISTS "Company";

CREATE TABLE "Company" (
    "id" SERIAL NOT NULL, "name" TEXT NOT NULL, "email" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Company_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Company_email_key" ON "Company"("email");

CREATE TABLE "User" (
    "id" SERIAL NOT NULL, "companyId" INTEGER NOT NULL, "name" TEXT NOT NULL,
    "email" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "role" TEXT NOT NULL DEFAULT 'driver',
    "status" TEXT NOT NULL DEFAULT 'active', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
ALTER TABLE "User" ADD CONSTRAINT "User_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE "Shift" (
    "id" SERIAL NOT NULL, "companyId" INTEGER NOT NULL, "driverId" INTEGER NOT NULL,
    "driverName" TEXT NOT NULL, "shiftDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "oilWaterChecked" BOOLEAN NOT NULL DEFAULT false, "fuelDrawn" TEXT NOT NULL DEFAULT '',
    "adBlueDrawn" TEXT NOT NULL DEFAULT '', "nightOut" BOOLEAN NOT NULL DEFAULT false,
    "expenses" TEXT NOT NULL DEFAULT '', "delaysNote" TEXT NOT NULL DEFAULT '',
    "defectsNote" TEXT NOT NULL DEFAULT '', "status" TEXT NOT NULL DEFAULT 'draft',
    "submittedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Shift_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "Shift" ADD CONSTRAINT "Shift_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Shift" ADD CONSTRAINT "Shift_driverId_fkey" FOREIGN KEY ("driverId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE "ShiftSegment" (
    "id" SERIAL NOT NULL, "shiftId" INTEGER NOT NULL, "segmentNumber" INTEGER NOT NULL,
    "truckReg" TEXT NOT NULL, "trailerReg" TEXT, "odometerStart" INTEGER NOT NULL,
    "odometerEnd" INTEGER, "startTime" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "endTime" TIMESTAMP(3), "truckChecks" JSONB NOT NULL, "trailerChecks" JSONB,
    "notes" TEXT NOT NULL DEFAULT '', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ShiftSegment_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "ShiftSegment" ADD CONSTRAINT "ShiftSegment_shiftId_fkey" FOREIGN KEY ("shiftId") REFERENCES "Shift"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE "DeliveryTask" (
    "id" SERIAL NOT NULL, "shiftId" INTEGER NOT NULL, "segmentId" INTEGER NOT NULL,
    "materials" TEXT NOT NULL DEFAULT '', "collectFrom" TEXT NOT NULL DEFAULT '',
    "deliverTo" TEXT NOT NULL DEFAULT '', "ticketNo" TEXT NOT NULL DEFAULT '',
    "startTime" TEXT NOT NULL DEFAULT '', "finishTime" TEXT NOT NULL DEFAULT '',
    "hours" TEXT NOT NULL DEFAULT '', "mileage" TEXT NOT NULL DEFAULT '',
    "tonnes" TEXT NOT NULL DEFAULT '', "kgs" TEXT NOT NULL DEFAULT '',
    "notes" TEXT NOT NULL DEFAULT '', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "DeliveryTask_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "DeliveryTask" ADD CONSTRAINT "DeliveryTask_segmentId_fkey" FOREIGN KEY ("segmentId") REFERENCES "ShiftSegment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
