import { z } from "zod";

const JobPartSchema = z.object({
  sequenceNumber:             z.number().int().min(0),
  type:                       z.string().min(1),
  savedLocationId:            z.number().int().nullable().optional(),
  siteName:                   z.string().optional(),
  unitName:                   z.string().optional(),
  street:                     z.string().optional(),
  town:                       z.string().optional(),
  postcode:                   z.string().optional(),
  locationTextSnapshot:       z.string().default(""),
  lat:                        z.number().nullable().optional(),
  lng:                        z.number().nullable().optional(),
  gateLat:                    z.number().nullable().optional(),
  gateLng:                    z.number().nullable().optional(),
  timeWindowStart:            z.string().nullable().optional(),
  timeWindowEnd:              z.string().nullable().optional(),
  bookedTime:                 z.string().nullable().optional(),
  earliestArrivalMinutes:     z.number().int().nullable().optional(),
  unloadingAllowanceMinutes:  z.number().int().nullable().optional(),
  standingChargeNote:         z.string().optional(),
  contactName:                z.string().optional(),
  contactPhone:               z.string().optional(),
  referenceNumber:            z.string().optional(),
  instructions:               z.string().optional(),
  contactEmail:               z.string().optional(),
  bookingRequired:            z.boolean().optional(),
  bookingRef:                 z.string().optional(),
  openingHours:               z.string().optional(),
  locationType:               z.string().optional(),
  navigationInstructions:     z.string().optional(),
  numPallets:                 z.number().int().nullable().optional(),
  internalNotes:              z.string().optional(),
  country:                    z.string().optional(),
  addressLine2:               z.string().optional(),
  countyRegion:               z.string().optional(),
});

const LoadDetailsSchema = z.object({
  quantity:           z.union([z.number(), z.string(), z.null()]).optional(),
  unit:               z.string().optional(),
  weight:             z.union([z.number(), z.string(), z.null()]).optional(),
  volume:             z.union([z.number(), z.string(), z.null()]).optional(),
  materialType:       z.string().optional(),
  hazardClass:        z.string().optional(),
  notes:              z.string().optional(),
  dimensions:         z.string().optional(),
  fragile:            z.boolean().optional(),
  stackable:          z.boolean().optional(),
  tempControlled:     z.boolean().optional(),
  tempRange:          z.string().optional(),
  photosRequired:     z.boolean().optional(),
  weighbridgeRequired:z.boolean().optional(),
  forkliftRequired:   z.boolean().optional(),
  tailLiftRequired:   z.boolean().optional(),
  craneRequired:      z.boolean().optional(),
  loadingMethod:      z.string().optional(),
  unloadingMethod:    z.string().optional(),
});

const JobCommonFields = z.object({
  customerId:               z.number().int().nullable().optional(),
  customerName:             z.string().optional(),
  assignedDriverId:         z.number().int().nullable().optional(),
  plannedDate:              z.string().optional(),
  templateId:               z.number().int().optional(),
  pickupLocationId:         z.number().int().optional(),
  dropoffLocationId:        z.number().int().optional(),
  pickupTextSnapshot:       z.string().optional(),
  dropoffTextSnapshot:      z.string().optional(),
  referenceNumber:          z.string().optional(),
  materialType:             z.string().optional(),
  quantityExpected:         z.string().optional(),
  quantityUnit:             z.string().optional(),
  plannerNotes:             z.string().optional(),
  assignedTruck:            z.string().optional(),
  assignedTrailer:          z.string().optional(),
  vehicleClass:             z.string().optional(),
  vehicleClassRequired:     z.string().optional(),
  reqBodyCategory:          z.string().optional(),
  reqGvwMin:                z.string().optional(),
  reqBodyType:              z.string().optional(),
  reqEquipment:             z.array(z.string()).optional(),
  reqLicenceClass:          z.string().optional(),
  trailerTypesAllowed:      z.array(z.string()).optional(),
  priority:                 z.enum(["low", "normal", "high"]).optional(),
  serviceType:              z.string().optional(),
  internalNotes:            z.string().optional(),
  stops:                    z.array(JobPartSchema).optional(),
  loadDetails:              LoadDetailsSchema.nullable().optional(),
  saveMode:                 z.enum(["draft", "ready_to_plan"]).optional(),
  requireCollection:        z.boolean().optional(),
  requirePOD:               z.boolean().optional(),
  requireDeliveryQty:       z.boolean().optional(),
  sequence:                 z.number().int().optional(),
  jobType:                  z.string().optional(),
  jobTitle:                 z.string().optional(),
  customerRef:              z.string().optional(),
  purchaseOrderNumber:      z.string().optional(),
  bookingContactName:       z.string().optional(),
  bookingContactPhone:      z.string().optional(),
  bookingContactEmail:      z.string().optional(),
  billingNotes:             z.string().optional(),
  customerInstructions:     z.string().optional(),
  custRefRequired:          z.boolean().optional(),
  poRequired:               z.boolean().optional(),
  minVehicleSize:           z.string().optional(),
  equipmentRequired:        z.array(z.string()).optional(),
  driverQualificationsReq:  z.array(z.string()).optional(),
  heightRestriction:        z.string().optional(),
  weightRestriction:        z.string().optional(),
  lengthRestriction:        z.string().optional(),
  vehicleAccessNotes:       z.string().optional(),
  failureAction:            z.string().optional(),
  assistancePhone:          z.string().optional(),
  assistanceNote:           z.string().optional(),
  returnDestination:        z.string().optional(),
  altAddress:               z.record(z.string(), z.unknown()).nullable().optional(),
});

export const CreateJobSchema = JobCommonFields.extend({
  saveAsTemplate: z.boolean().optional(),
  templateName:   z.string().optional(),
});

export const PatchJobSchema = JobCommonFields;

export const UpdateJobStatusSchema = z.object({
  status:          z.string().min(1, "Status is required"),
  note:            z.string().optional(),
  actualQuantity:  z.string().optional(),
  actualUnit:      z.string().optional(),
  collectionNote:  z.string().optional(),
  podNumber:       z.string().optional(),
  deliveryNote:    z.string().optional(),
  clientEventId:   z.string().uuid("clientEventId must be a UUID").optional(),
  clientTimestamp: z.string().optional(),
  gpsLat:          z.number().min(-90).max(90).optional(),
  gpsLng:          z.number().min(-180).max(180).optional(),
});

export const AddJobNoteSchema = z.object({
  note: z.string().min(1, "Note cannot be empty"),
});

export type CreateJobBody        = z.infer<typeof CreateJobSchema>;
export type PatchJobBody         = z.infer<typeof PatchJobSchema>;
export type UpdateJobStatusBody  = z.infer<typeof UpdateJobStatusSchema>;
export type AddJobNoteBody       = z.infer<typeof AddJobNoteSchema>;
